### ISSUE TITLE
Google Play Billing 4.0 is no longer supported

### ISSUE THREAD

**Issue by CameronVetter** [Kebechet/Maui.RevenueCat.InAppBilling#11]
I attempted to submit an app built with this package to through the google play console.  This results in this error message:

![image](https://github.com/Kebechet/Maui.RevenueCat.InAppBilling/assets/7763701/bda01385-4a0c-4df1-8606-68f332d6c75c)

Per the deprecation FAQ this has long been unsupported:

https://developer.android.com/google/play/billing/deprecation-faq

The problematic library in question is: 

Xamarin.Android.Google.Billing Client 4.0.0

This transitive library is brought in by this package as shown here:

![image](https://github.com/Kebechet/Maui.RevenueCat.InAppBilling/assets/7763701/042c01ac-c172-44e9-bdee-212353f9dc60)

I believe the only way to resolve this is to update to a newer version of the Xamarin.RevenueCat.Android library.  I'm curious to hear what others are doing though, since I assume I am not the first to attempt to upload to the google play store.

**Comment by CameronVetter** [comment]
A likely related issue here: https://github.com/thisisthekap/Xamarin.RevenueCat.Android/issues/44

**Comment by Kebechet** [comment]
@CameronVetter I think this is their new repo: https://github.com/thisisthekap/Tonestro.Maui.RevenueCat.Android
once they fix this we will update the packege

**Comment by CameronVetter** [comment]
Looks that way and it appears that the last release targets 5.1.0.1 instead of 4.0.0.0  .  What did you see that needs fixing?  (Just wondering if there is anything I can do to help.

**Comment by Kebechet** [comment]
I dont remember, I know I checked that some time ago and for some reason I didnt update it yet.
I will check it today

**Comment by Kebechet** [comment]
So the reason I didnt update it that time was simple... breaking changes 😅 
So I updated the package and fixed those breaking changes. Tomorrow I will replace all obsolete functions and I will test it and if everything goes well I will create a PR for you to check before I merge it.

**Comment by CameronVetter** [comment]
Sounds great, I'll watch for the PR!

**Comment by CameronVetter** [comment]
> Any progress on this?

The latest nuget package resolves this if you update your package.

**Comment by malatx** [comment]
I created a new bindings for RC 7.0.1 that does not require Maui.
