### ISSUE TITLE
iOS - slow payment speed

### ISSUE THREAD

**Issue by Kebechet** [Kebechet/Maui.RevenueCat.InAppBilling#3]
On iOS devices it takes quite some time to load UI for payment
and also after confirming the payment it again takes a few seconds to load popup of successful payment.

It seems to be something similar to problem from Flutter binding, even though there should be any connection between iOS native library and flutter native lib:
https://github.com/RevenueCat/purchases-flutter/issues/693

Where can lie this problem:
- Directly in RevenueCat iOS library 
  - maybe just the version we use ? 
- In iOS binding - probably this binding requires some special flags for building ?
- wrapper or final app - where we have specified different things like:
  - `<MtouchUseLlvm>true</MtouchUseLlvm`
  - `<MtouchLink>SdkOnly</MtouchLink>`
  - `<UseInterpreter>true</UseInterpreter>`
  - from which theoretically something (e.g. interpreter) could slow down the app/binding

Investigate all possibilities and try to fix it.

PS: We experienced this problem also with [another 3rd party iOS binding](https://github.com/thisisthekap/Tonestro.Maui.RevenueCat.iOS)

**Comment by Kebechet** [comment]
Hello @Lyesbcb 
React SDK is officially supported by revenuecat, so I would suggest you to directly create and issue in their react repo:
https://github.com/RevenueCat/react-native-purchases

Unfortunately I wasnt able to find a solution for now but if it is something directly in the SDK they should be able to fix it.

**Comment by Kebechet** [comment]
@Lyesbcb so when you released the app into the store it is fast ? Or they just claim that ?

**Comment by Lyesbcb** [comment]
@Kebechet I released the app into App Store in production and it is fast (like others app).

**Comment by Kebechet** [comment]
As discussed the speed for payment process is slow only in Sandbox, in production environment it works well.
Closing
