### ISSUE TITLE
Expose a method to get current CustomerInfoDto

### ISSUE THREAD

**Issue by varyamereon** [Kebechet/Maui.RevenueCat.InAppBilling#33]
It occurs to me that it would be a good idea to included a method like `GetCustomerInfo()`, that just returns an updated version of the cached customer info. At the moment the only way to access this information is when we login and if we use restore purchases, any other time we don't have a way of accessing things like up to date information about the user's subscription or active entitlements.

I appreciate that the aim of this library is to extract things like this away, but if we are giving access to CustomerInfoDto at other times in the app, we should be able to get a current version of it on demand. Would make sense to implement along with #22 in my opinion.

**Comment by Kebechet** [comment]
Makes sense. When I looked into Bindings they directly expose: `GetCustomerInfoAsync` so it should be pretty straight-forward to implement. It even seems to be used in our wrapper `GetManagementSubscriptionUrl`. 

Feel free to create PR.

**Comment by Kebechet** [comment]
PR merged and new version released. Thank you for the implementation!

https://www.nuget.org/packages/Kebechet.Maui.RevenueCat.InAppBilling/4.2.0
