### ISSUE TITLE
App cannot be built for iOS simulator

### ISSUE THREAD

**Issue by dimangulov** [Kebechet/Maui.RevenueCat.InAppBilling#41]
NET 8.0
Nuget version 4.5.0

I try to build and run the solution in a iOS simulator to check additional layouts, but no luck so far

error : ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/anastasiavalter/Library/Caches/Xamarin/mtbs/builds/Mia.Mobile.Shared.Maui/bc09ed9c847d5998ec9366dd658c36ac7eedcea8ef971e0a2ef3b0032d445152/obj/Debug/net8.0-ios/iossimulator-arm64/linker-cache/RevenueCat.framework/RevenueCat'

**Comment by Kebechet** [comment]
What Mac do you use ? With Intel or M1 CPU ?

**Comment by dimangulov** [comment]
Macbook Air M1

Thanks a lot for your time!

**Comment by dimangulov** [comment]
Works in 4.5.2, thanks a lot!
