### ISSUE TITLE
Kebechet.Maui.RevenueCat.iOS - 4.31.9.2 package is broken

### ISSUE THREAD

**Issue by dimangulov** [Kebechet/Maui.RevenueCat.InAppBilling#42]
If I try to install the package

Kebechet.Maui.RevenueCat.iOS - 4.31.9.2

I got the error

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		Could not find a part of the path 'C:\Users\diman\.nuget\packages\kebechet.maui.revenuecat.ios\4.31.9.2\lib\net8.0-ios17.2\Maui.RevenueCat.iOS.resources\RevenueCat.xcframework\ios-arm64_x86_64-simulator\RevenueCat.framework\Modules\RevenueCat.swiftmodule\arm64-apple-ios-simulator.private.swiftinterface'.

**Comment by Kebechet** [comment]
Hello @dimangulov
thanks for the report. In following days I will take a look.
Deploy on real devices works well ?

**Comment by dimangulov** [comment]
The package cannot be installed, because of the error

**Comment by Kebechet** [comment]
This seems to be caused by: https://developercommunity.visualstudio.com/t/Allow-building-running-and-debugging-a/351628
I have tried to remove redundant files to shorten final paths and we will see if you will be able to install latest version when I release it

**Comment by Kebechet** [comment]
Try https://www.nuget.org/packages/Kebechet.Maui.RevenueCat.InAppBilling/4.5.1
and then let me know if now you can install the package

**Comment by dimangulov** [comment]
Looks like the package **Kebechet.Maui.RevenueCat.InAppBilling** still uses -> **Kebechet.Maui.RevenueCat.iOS** - 4.31.9.1 as a dependency.

If I try to install manually **Kebechet.Maui.RevenueCat.iOS** - 4.31.9.2, I get the same issue as before

Restoring packages for C:\w\suretint\Dispense\src\Mia.Mobile.Shared.Maui\Mia.Mobile.Shared.Maui.csproj...
  GET https://api.nuget.org/v3-flatcontainer/kebechet.maui.revenuecat.ios/index.json
  GET https://pkgs.dev.azure.com/hexagonmi/e2c20100-24d5-47f1-976a-24d5ada56982/_packaging/d9925a07-94d0-4765-8831-9bf2590311fb/nuget/v3/flat2/kebechet.maui.revenuecat.ios/index.json
  OK https://api.nuget.org/v3-flatcontainer/kebechet.maui.revenuecat.ios/index.json 303ms
  GET https://api.nuget.org/v3-flatcontainer/kebechet.maui.revenuecat.ios/4.31.9.2/kebechet.maui.revenuecat.ios.4.31.9.2.nupkg
  NotFound https://pkgs.dev.azure.com/hexagonmi/e2c20100-24d5-47f1-976a-24d5ada56982/_packaging/d9925a07-94d0-4765-8831-9bf2590311fb/nuget/v3/flat2/kebechet.maui.revenuecat.ios/index.json 359ms
  OK https://api.nuget.org/v3-flatcontainer/kebechet.maui.revenuecat.ios/4.31.9.2/kebechet.maui.revenuecat.ios.4.31.9.2.nupkg 278ms
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\diman\.nuget\packages\kebechet.maui.revenuecat.ios\4.31.9.2\lib\net8.0-ios17.2\Maui.RevenueCat.iOS.resources\RevenueCat.xcframework\ios-arm64_x86_64-simulator\RevenueCat.framework\Modules\RevenueCat.swiftmodule\arm64-apple-ios-simulator.private.swiftinterface'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

**Comment by Kebechet** [comment]
Sorry, my bad I forgot to bump iOS package and link it to main wrapper. Try v4.5.2 (it is in process of publishing):
https://www.nuget.org/packages/Kebechet.Maui.RevenueCat.InAppBilling/4.5.2

+try the simulator run as well, I didnt get the build error for iOS simulator with this version

**Comment by dimangulov** [comment]
Works, thanks a lot!

**Comment by Kebechet** [comment]
This issue is resolved but potentially it can happen if the main repo has really long path. Workaround for that should be using:
```
<UseLegacyPathHandling>false</UseLegacyPathHandling>
<UseLongPaths>true</UseLongPaths>
```
in `.csproj`

reference:
https://developercommunity.visualstudio.com/t/Allow-building-running-and-debugging-a/351628#T-N10757314
