### ISSUE TITLE
IOS - Unable to check Intro offer elegibility status

### ISSUE THREAD

**Issue by CameronVetter** [Kebechet/Maui.RevenueCat.InAppBilling#9]
In order to check intro offer eligibility status with IOS, the method "CheckTrialOrIntroDiscountEligibility" is used.  This has not been exposed as part of the API yet.  I will create a PR to introduce this functionality.

**Comment by Kebechet** [comment]
Thank you for the PR.
Merged and published as [v1.1.0](https://www.nuget.org/packages/Kebechet.Maui.RevenueCat.InAppBilling/1.1.0)
